// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvhmqxesuunhriwcnxhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2aG1xeGVzdXVuaHJpd2NueGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDU4MTYsImV4cCI6MjA2NzAyMTgxNn0.Qe_2mOIDD_mBv7XEfVXaOZRn2lXhxsnWH5ov_nBXYQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});